use_frameworks!
platform :ios, '8.0'

target 'YSBannerView_Example' do
  pod 'YSBannerView', :path => '../'

  pod 'SDWebImage'
  pod 'YYWebImage'
  
  target 'YSBannerView_Tests' do
    inherit! :search_paths
  end
end
